### ISSUE TITLE
classes.dex not found inside apk due to dex optimisation

### ISSUE THREAD

**Issue by Abdelhak-Bahri** [MassyB/BaksmaliApp#1]
I got the exception DexFileNotFound

> org.jf.dexlib2.DexFileFactory$DexFileNotFound: zip file TelephonyProvider.apk does not contain a classes.dex file

 
The exception is made by Smali library  when the file classes.dex is not found on the apk archive , this is possible when dex-preoptimization is enabled. 

an .odex file (Email.odex for instance, just next to Email.apk) will be generated from the classes.dex and the original classes.dex is stripped from the apk.
reference : http://stackoverflow.com/a/19887662

**Comment by MassyB** [comment]
So, instead of specifying the `.apk` file you have to specify the `.odex` file. the Baksmali tool handle this use case.
